blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.AllPosts.as_view(), name='all_blogs'),
    path('<int:post_id>/', views.Detail.as_view(), name='detail'),
    path('rewiew/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
]

password_generator/urls.py
from django.urls import path
from . import views

app_name = 'password_generator'

urlpatterns = [
    path('', views.generator, name='generator'),
    path('password', views.password, name='password')
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('generator/', include('password_generator.urls')),
    path('randomizer/', include('randomizer.urls')),
    path('shortener/', include('shortener.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

randomizer/urls.py
from django.urls import path
from . import views

app_name = 'randomizer'

urlpatterns = [
    path('', views.generate_number, name='number_generator'),
    path('number', views.random_number, name='number')
]

shortener/urls.py
from django.urls import path
from . import views

app_name = 'shortener'

urlpatterns = [
    path('', views.short, name='short'),
    path('number', views.short_link, name='short_link')
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=250)
    date = models.DateField()
    content = RichTextField(blank=True)

    def __str__(self):
        return self.title


class Comments(models.Model):
    name = models.CharField('Name', max_length=30)
    email = models.EmailField()
    text = models.TextField('Comment', max_length=500)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'Comments'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return f'{self.name}, {self.post}'

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

shortener/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.base import View
from .models import Post
from .form import CommentsForm


class AllPosts(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/all_blogs.html', {'posts': posts})


class Detail(View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        return render(request, 'blog/detail.html', {'post': post})


class AddComments(View):
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/blog/{pk}')

password_generator/views.py
import random
import string

from django.shortcuts import render


def generator(request):
    return render(request, 'password_generator/generator.html', context={'range': range(6, 21)})


def password(request):
    characters = list(string.ascii_lowercase)
    length = int(request.GET.get('length', 8))
    password_parameters = {
        'uppercase': string.ascii_uppercase,
        'numbers': string.digits,
        'special': string.punctuation,
    }
    for parameter, value in password_parameters.items():
        if request.GET.get(parameter):
            characters.extend(value)

    the_password = ''
    for char in range(length):
        the_password += random.choice(characters)
    return render(request, 'password_generator/password.html', {'password': the_password})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

randomizer/views.py
from django.shortcuts import render
from random import randint


def generate_number(request):
    return render(request, 'randomizer/num_generator.html')


def random_number(request):
    start_diapason = int(request.GET.get('first_number'))
    end_diapason = int(request.GET.get('second_number'))
    try:
        random_number = randint(start_diapason, end_diapason)
    except ValueError:
        return render(request, 'randomizer/num_generator.html', {'error': 'Please, enter a valid range!'})
    context = {
        'random_number': random_number,
        'start_diapason': start_diapason,
        'end_diapason': end_diapason
    }
    return render(request, 'randomizer/random_number.html', context)

shortener/views.py
import pyshorteners

from django.shortcuts import render


def short(request):
    return render(request, 'shortener/shortener.html')


def short_link(request):
    link = request.GET.get('url')
    shortener = pyshorteners.Shortener()
    short_link = shortener.tinyurl.short(link)
    return render(request, 'shortener/shorted_link.html', {'short_link': short_link})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

    <h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>
    <div>
        <h4 class="text-center mb-5">There are {{ posts.count }} post{{ posts.count|pluralize }}</h4>
    </div>
    {% for post in posts %}
        <div class="row justify-content-center my-3">
            <div class="col-md-10">
                <a href="{% url 'blog:detail' post.id %}"><h2>{{ post.title }}</h2></a>
                <h5 class="text-muted">{{ post.date|date:'d M Y' }}</h5>
                <h4>{{ post.content|safe|truncatechars:200 }}</h4>
            </div>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1 class="text-center mt-5" id="blogdetailtitle">{{ post.title }}</h1>
    <h2 class="text-center text-muted mb5">{{ post.date|date:"F jS Y" }}</h2>
    {{ post.content|safe }}
    <hr>
    <div class="text-left mt-3">
        <h3>Оставить комментарий</h3>
        <form action="{% url 'blog:add_comments' post.id %} " method="post">
            {% csrf_token %}
            <div>
                <textarea name="text" rows="4" cols="50" ></textarea>
             </div>
            <div class="mt-1">
                <lable>Ваше имя*</lable>
                <input type="text" name="name">
             </div>
                <div class="mt-1">
                <lable>Ваш email*</lable>
                <input type="email" name="email">
             </div>
                <div class="mt-1 mb-3">
                <input type="submit" name="" id="" class="btn btn-primary">
             </div>
        </form>
        <div>
            {% for comment in post.comments_set.all %}
                <hr>
                <div>
                <h4>{{ comment.name }}</h4>
                <p>{{ comment.text }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

password_generator/templates/password_generator/generator.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<div class="container text-center">
    <div>
         <h1>Generate your password</h1>
    </div>
    <div class="mt-3">
        <form action="{% url 'password_generator:password' %}">
            <select name="length">
                {% for i in range %}
                <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select> Length
            <div class="mt-2">
                <input type="checkbox" name="uppercase"> Uppercase
            </div>
            <div class="mt-2">
                <input type="checkbox" name="numbers"> Numbers
            </div>
            <div class="mt-2">
                <input type="checkbox" name="special"> Special Chars
            </div>
            <div class="mt-2">
                <input type="submit" value="Generate password" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock %}

password_generator/templates/password_generator/password.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<div class="container text-center">
        <div>
            <h1>Your password:</h1>
            <h2 class="alert alert-success">{{ password }}</h2>
        </div>
        <div>
            <h4>
            <a href="{% url 'password_generator:generator' %}" class="btn btn-warning">Generate New</a>
            </h4>
        </div>
 </div>

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap" rel="stylesheet">
    <link rel="icon" type="image.png" href="{% static 'portfolio/Zeronet_logo.png' %}">
    <title>Yuri Shepel</title>
</head>
<body>
<nav id="topNav" class="navbar navbar-expand-md navbar-light" style="background-color: #74b9ff;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'portfolio/Zeronet_logo.png' %}" width="30" height="30"
                 class="d-inline-block alingh-top" alt="Yuri's Logo">
            <span>Yuri Shepel</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}">Resume</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/YuriShepel" target="_blank">Github</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.facebook.com/profile.php?id=100000759147803" target="_blank">Facebook</a>
                </li>
                <li>
                    <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<div class="row justify-content-center mb-3">
    <div class="mt-3">
        <img src="{% static 'portfolio/me.jpg' %}" alt="" width="300">
    </div>
    <div>
        <h1 id="hometext" class="font-weight-bold">Yuri Shepel's portfolio and blog 😊</h1>
    </div>
</div>
    <h2 class="mt-5">Portfolio</h2>
    <hr>
<div class="row">
    {% for project in projects %}
        <div class="col-lg-4 col-md-6">
        <img src="{{ project.image.url }}" width="300" height="150" alt="">
        <h2><a href="{{ project.url }}">{{ project.title }}</a></h2>
        <p>{{ project.description }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

randomizer/templates/randomizer/num_generator.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<div class="container text-center">
    <div>
         <h1>Generate random number</h1>
    </div>
    <div>
        <h2>Select range:</h2>
    </div>
    <div class="mt-3">
        <form action="{% url 'randomizer:number' %}">
            <p>From</p>
            <div class="mt-2">
                <input type="number" name="first_number" value="1" min="0">
            </div>
            <p>to</p>
            <div class="mt-2">
                <input type="number" name="second_number" value="0" min="0">
            </div>
            <div class="mt-2">
                <input type="submit" value="Generate number" class="btn btn-primary">
            </div>
        </form>
    </div>
    <div class="mt-2">{{ error }}</div>
</div>
{% endblock %}

randomizer/templates/randomizer/random_number.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<div class="container text-center">
        <div>
            <h1>Random number:</h1>
            <h2 class="alert alert-success">{{ random_number }}</h2>
        </div>
        <div>
            <h4>
            <a href="{% url 'randomizer:number_generator' %}" class="btn btn-warning">Generate new number</a>
            </h4>
        </div>
 </div>

{% endblock %}

shortener/templates/shortener/shorted_link.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<div class="container text-center">
        <div>
            <h1>Your shorted link:</h1>
            <h2 class="alert alert-success">{{ short_link }}</h2>
        </div>
        <div>
            <h4>
            <a href="{% url 'shortener:short' %}" class="btn btn-warning">Short new link</a>
            </h4>
        </div>
 </div>
{% endblock %}

shortener/templates/shortener/shortener.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
<div class="container text-center">
    <div>
         <h1>Link shortener</h1>
    </div>
    <div>
        <h2>Please, enter your link</h2>
    </div>
    <div class="mt-3">
        <form action="{% url 'shortener:short_link' %}">
            <div class="mt-2">
                <input type="url" name="url" id="url" placeholder="https://example.com" pattern="https://.*" size="30" required>
            </div>
            <div class="mt-2">
                <input type="submit" value="Short" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock %}